[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/materias-primas"
to = "/src/pages/CardDisplay"

[[redirects]]
from = "/order-placement"
to = "/src/pages/CardDisplay"
